using System.IO;

namespace Nrk.FluentCore.Experimental.GameManagement.Dependencies;

public abstract class MinecraftDependency // TODO: Implement IDownloadable interface for downloading game dependencies
{
    /// <summary>
    /// Absolute path of the .minecraft folder
    /// </summary>
    public required string MinecraftFolderPath { get; init; }

    /// <summary>
    /// File path relative to the .minecraft folder
    /// </summary>
    public abstract string FilePath { get; } // Can be generated by derived types from their properties

    /// <summary>
    /// Absolute path of the file
    /// </summary>
    public string FullPath => Path.Combine(MinecraftFolderPath, FilePath);

    /// <summary>
    /// URL to download the file
    /// </summary>
    public abstract string Url { get; } // Can be generated by derived types from their properties

    /// <summary>
    /// Expected size of the file in bytes
    /// </summary>
    public required int Size { get; init; }

    /// <summary>
    /// Expected SHA1 of the file
    /// </summary>
    public required string Sha1 { get; init; }
}
