name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: Resource
      #     path: |
      #       .\Natsurainko.FluentCore\bin\Debug\net6.0\Natsurainko.FluentCore.dll
      #       .\Natsurainko.FluentCore\bin\Debug\Natsurainko.FluentCore.2.0.4.nupkg
